---
engines:
  csslint:
    enabled: true
    checks:
      ids:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: false
    checks:
      no-console:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
- test/
- bower_components/
